language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
before_install:
  - sudo apt-add-repository -y ppa:swi-prolog/stable
  - sudo apt-get update
  - sudo apt-get install -y swi-prolog-nox # >=8.2.0
install:
  - pip install -r test-requirements.txt coveralls
script:
  - make cover
after_success:
  - coveralls
